version: "3"
networks:
  wasnet: {}
services:
  node:
    image: was855:node
    depends_on: 
      - "dmgr"
    ports: 
      - "9080"
    networks:
      - wasnet
    stop_grace_period: 2m
  dmgr:
    image: was855:dmgr
    ports: 
      - "9060:9060"
      - "9043:9043"
    networks:
      - wasnet